; Script generated by Antigravity for BodegasKeyla
; Logic: Uses the already bundled release\win-unpacked folder

[Setup]
AppId={{com.neu360.bodegaskeyla}}
AppName=BodegasKeyla
AppVersion=1.1.0
AppPublisher=Neu360
DefaultDirName={autopf}\BodegasKeyla
DefaultGroupName=BodegasKeyla
AllowNoIcons=yes
; Icono del instalador
SetupIconFile=public\app_icon.png
Compression=lzma
SolidCompression=yes
WizardStyle=modern
OutputDir=Output
OutputBaseFilename=BodegasKeyla_v1.1.0_Setup

[Languages]
Name: "spanish"; MessagesFile: "compiler:Languages\Spanish.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked

[Files]
Source: "release\win-unpacked\BodegasKeyla.exe"; DestDir: "{app}"; Flags: ignoreversion
Source: "release\win-unpacked\*"; DestDir: "{app}"; Flags: ignoreversion recursesubdirs createallsubdirs

[Icons]
Name: "{group}\BodegasKeyla"; Filename: "{app}\BodegasKeyla.exe"; IconFilename: "{app}\app_icon.png"
Name: "{commondesktop}\BodegasKeyla"; Filename: "{app}\BodegasKeyla.exe"; Tasks: desktopicon

[Run]
Filename: "{app}\BodegasKeyla.exe"; Description: "{cm:LaunchProgram,BodegasKeyla}"; Flags: nowait postinstall skipifsilent
